### ISSUE TITLE
Fix issue when adding fields per prospector

### ISSUE THREAD

**Issue by vmcano** [elastic/filebeat#137]
I am using the following configuration to send logs to Logstash with Filebeat:

````
        -
      paths:
        - /logs/test.log
      fields:
        type: test
````
As you can see, I am trying to add more information like type but the field that Logstash receives is "field.type". I guess this is a malfunctioning and it should be simply "type".

**Comment by ruflin** [comment]
@vmcano As we are sending JSON to logstash, it should actually retrieve the following: 
`"fields":{"type":"test"}` I briefly tried it on my machine with the following settings:

```
filebeat:
  # List of prospectors to fetch data
  prospectors:
    -
      # Paths that should be crawled and fetched
      paths:
        - /var/log/*.log
      fields:
        hello: world
        name: ruflin
```

Inside elasticsearch I got the following output after it was sent through logstash:
```
"fields":{"hello":"world","name":"ruflin"}
```

What is the logstash configuration you are using? Which plugin are you using?

**Comment by vmcano** [comment]
When I said I get "field.type" I meant the field "type" was inside the field "fields". So, the result that both of us get is the same. Sorry for not explaining it well.

However, if I set the previous configuration, I expect the field "type" to be modified, and not a new field inside a field called "fields". So what I expect from your example would be:
````
"hello":"world",
"name":"ruflin",
````

Wouldn't it make more sense to modify existing fields or to create first level fields instead of grouping all of them under a field called "fields"?

**Comment by ruflin** [comment]
If we don't group the fields under `fields` we have the risk of conflicting with other data entries. Already in your case would be a conflict, as the field `type` is already in use.

Is using "subfields" preventing you from doing some queries or things you were doing before?

**Comment by vmcano** [comment]
This functioning is a little different from the functioning of Logstash-Forwarder, but in my case I only have to change the configuration of some Logstash filters. However, this could lead to bigger changes for other people.
Regarding to queries, I didn't have any problem.

**Comment by ruflin** [comment]
@vmcano Good to know. It means we should mention this in the migration guide from logstash-forwarder. https://github.com/elastic/filebeat/issues/138

What other potential bigger changes were you thinking of?

**Comment by vmcano** [comment]
@ruflin I didn't have to do many changes. Migration from Logstash-Forwarder to Filebeat was quite smooth.
A thing that I missed was a more comprehensive log in Filebeat, because even with the `logging` option in the configuration file, there is too little information.

**Comment by ruflin** [comment]
Any specific log outputs you were missing / looking for?

**Comment by vmcano** [comment]
Logs produced by Logstash-Forwarder are really helpful as they give you the opportunity to check if connection is correctly established, if file is being harvested and at what point... I'd like to have this information in Filebeat because looking for errors is difficult without it.

At the moment, the `logging` part of my config file looks like this:
````
logging:
  # Enable file rotation with default configuration
  to_files: true

  # Do not log to syslog
  to_syslog: false

  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 10
````
And after 20 hours working, I have no information at all.
