### ISSUE TITLE
Filebeat :  fail to use the console output 

### ISSUE THREAD

**Issue by beta-beta** [elastic/filebeat#159]
The config file:
```
output:
   console:
      enabled: true
      pretty: true
```
Error:  CRIT No outputs are defined. Please define one under the output section
