### ISSUE TITLE
Filebeat does not tail log files on Windows when encoding is set to UTF-8

### ISSUE THREAD

**Issue by DanielLaberge** [elastic/filebeat#167]
When I start filebeat, it sends all new log entries to logstash as expected, **but then it stops after reaching the end of the log files and does not send new entries as they are added.** 

This is blocking me from using filebeat, any guidance would be much appreciated.

Using the latest nightly build (filebeat-nightly.151030140642-windows.zip).

Tested on Windows 8.1 Pro x64 on an NTFS file system and Windows Server 2012 R2 on NTFS with the same results.

**Filebeat log:**
````
C:\logs\filebeat>filebeat.exe -c filebeat.yml -v
geolite.go:52: WARN Couldn't load GeoIP database
publish.go:222: WARN No output is defined to store the topology. The server fields might not be filled.
publish.go:234: INFO No shipper name configured, using hostname 'PC-Dan'
registrar.go:75: INFO Loading registrar data from C:\logs\filebeat/.filebeat
crawler.go:77: INFO All prospectors initialised with 2 states to persist
service_windows.go:45: ERR Error: The service process could not connect to the service controller.
```
**Filebeat config file:**
```
filebeat:
  prospectors:
    -
      paths:
        - C:\logs\Frontend.trace.log

      fields:
        app: "FE"

      encoding: utf-8
      type: log
      ignore_older: 10m
      scan_frequency: 10s
    -
      paths:
        - C:\logs\Services.trace.log

      fields:
        app: "SVC"

      encoding: utf-8
      type: log
      ignore_older: 10m
      scan_frequency: 1s

  idle_timeout: 1s

############################# Output ##########################################
output:

  logstash:
    enabled: true

    hosts: ["myLogstashHost:5044"]

shipper:
```
