### ISSUE TITLE
Registrar debug is wrong when using absolute registry_file path

### ISSUE THREAD

**Issue by andrewkroh** [elastic/filebeat#172]
My config is:

```
--- 
  filebeat: 
    registry_file: /var/lib/filebeat/registry
    prospectors: 
      - paths: 
          - /var/log/messages
  logging: 
    to_files: true
    files: 
      path: /var/log
      name: filebeat
    to_syslog: false
  output: 
    elasticsearch: 
      enabled: true
      hosts: 
        - "localhost:9200"
  shipper: 
    tags: 
      - digitalocean
    name: cloud
```

When starting filebeat with a CWD of `/var/log`, the debug output is:

```
registrar.go:60: DBG  Registry file set to: /var/lib/filebeat/registry
registrar.go:75: INFO Loading registrar data from /var/log//var/lib/filebeat/registry
```
