### ISSUE TITLE
filebeat logging does not include a timestamp

### ISSUE THREAD

**Issue by nheath** [elastic/filebeat#223]
I have been testing filebeat RC1 in windows as a replacement for logstash-forwarder. I've enabled filebeat logging in filebeat.yml, and am running filebeat from the console with `.\filebeat.exe -c .\filebeat.yml`

The relevant part of my YAML config is pretty much stock
```
logging:
  to_files: true
  level: debug
  files:
    path: C:\logstash-filebeat\logs\
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 7
```

I see events with timstamps on the console output, e.g.

```
2015/11/11 21:10:38.002329 prospector.go:180: DBG  Start next scan
2015/11/11 21:10:38.002329 prospector.go:201: DBG  scan path C:\Logs\*\*.log
2015/11/11 21:10:38.004645 prospector.go:213: DBG  Check file for harvesting: C:\Logs\WebSite\WebSite.log
```

but in `filebeat.log` there are no timestamps
```
DBG  Start next scan
DBG  scan path C:\Logs\*\*.log
DBG  Check file for harvesting: C:\Logs\WebSite\WebSite.log
```
