### ISSUE TITLE
Logstash output randomly loses records based on spool_size

### ISSUE THREAD

**Issue by roji** [elastic/filebeat#226]
I'm trying to set up filebeat rc1 to ship logs to logstash and am running into a strange issue. My config is set up to harvest exactly one file, and I clean the state before starting to make filebeat start at the beginning of the file. With the default spool_size (1024), I can see that only around 10 out of 600 events are actually shipped to logstash and inserted into elasticsearch. My filebeat config also has the file output configured, and I can see all events in the file, pointing to a problem with the filebeat-logstash interaction.

As I reduce the spool_size parameter, the number of lost records is reduced, and at spool_size == 5 everything is shipped correctly. Note that idle_timeout is configured to 5s - according to the docs this should make filebeat ship all records eventually, but this doesn't happen.

My config:

```yml
filebeat:
  prospectors:
    -
      paths:
        - /tmp/some_file.log

      fields:
        instance: some_id
      fields_under_root: true
      ignore_older: 24h
      document_type: some_type

  spool_size: 100
  idle_timeout: 5s
  registry_file: /var/lib/filebeat/registry
  config_dir:

output:
  logstash:
    enabled: true
    hosts: ["elk.eaglelabs.local:5044"]

  file:
    enabled: true
    path: "/tmp/filebeat"
    filename: filebeat

shipper:
```
