### ISSUE TITLE
Proposal Multiline Implementation

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#301]
# Multiline Proposal

The following is the proposal for the implementation of the multiline feature in filebeat. It is heavily inspired by the implementation of [multiline in Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-multiline.html) and tries to improve on top of it.

The multiline feature should enable the user to configure filebeat in a way, that filebeat can automatically detect events which appear in the log file on multiple lines but belong to one event. This is for example the case for Java Stack traces.

## Cases

There are 5 different cases which should be covered by the implementation. Examples of the event types which are referred to can be found on the bottom.

### Start Pattern is known

The pattern of the first line is known. All follow up lines belong to the first line. An example here is the Java Stack Trace. By defining the pattern of the first line of the event, all follow up lines which don't match the pattern belong to the same event. A regexp could be defined that each line starting with `[` is the start of the event. All follow up lines which don't match, will be added to the event.

The challenge in defining the start pattern, the full event can only be detected if an additional event is added to the file which again matches the start pattern.

### After Pattern is known
The pattern of the events after the first line of the event is known. A good example here is again the Java Stack Trace. Ever line which starts with a space or tab belongs to the previous line. This has the same affect as the start pattern, but one or the other can be chosen based on which one is easier to define.

### Before Pattern is known
Similar to the after pattern, the before pattern knows what that pattern is of all lines except the last one. A good example here is the C line continuation. A before pattern is created which matches all lines ending with `\`.

### End Pattern is known
All lines are combined to an event until the end pattern is matched. This could be used for XML or JSON outputs. For xml a line starting with `</` could be defined, for JSON a line starting with `}`. The advantage over using the start pattern for XML and JSON is, that the event can be sent directly before and additional event is added.

### Start and end Pattern is known
The start and end pattern can be combined, to send all events in between. For XML or JSON start and end pattern can be defined which makes it very accurate to define which lines are combined together. The advantage over only using the end pattern, is that combining lines only starts after the start pattern is matched.

### Config Options
Based on the above, the following config options are suggested available inside each prospector.

```
# General feature to limit the maximum size of an event. This is especially useful
# for multiline events. All events longer the max_bytes will be truncated.
max_bytes: int

# Enable mutline feature
multiline:
  # See description of start_pattern. Can be used alone and in combination with end_pattern
  start_pattern: regexp

  # See description of end_pattern. Can be used alone and in combination with start_pattern
  end_pattern: regexp

  # See description of after_pattern. Can only be used alone
  after_pattern: regexp

  # See description of before_pattern. Can only be used alone
  before_pattern: regexp

  # Maximum number of lines which are combined into one event
  max_lines: int

  # Timeout after reading the last line to flush multline event
  # This is needed especially for start_pattern in case no new lines are added
  # and it can't be said if event is completed.
  timeout: duration
```

### Event sent

The event which is sent after combining multiple lines, has some additional flags:
* multiline: set to true if event consists out of multiple lines
* lines: Number of lines combined.
* truncated: True if the event was truncated. Should be added as general field.

### Questions

* What happens to events after max_lines or max_bytes is reached?
  * Will the content be truncated?
  * Should the content be sent as a second event with a flag so LS can combine the events again?
* Memory usage?

### Comparison Logstash

The implementation on the Logstash side only uses 3 variables instead of 4 above. I see two advantages using the variables above:

* Start / End Pattern can be combined
* Variable names are more descriptive

### Java Stack Trace
```
[beat-logstash-int-multiple-big-tls-832-2015.11.28] IndexNotFoundException[no such index]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
```

### C Line Continuation
```
This is \
a mutli \
line event \
I think
```

### XML
```
<html>
  <title>Nicolas Ruflin</title>
  <body>
    This is a blog
  </body>
</html>
```

### JSON
```
{
  "name" : "Arlok",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by tilmans** [comment]
I would vote for max_line and max_bytes to results in truncation, remaining data is not sent. This way the receiver can be protected from excessive data. If truncation occurs and is not desired then the limit should be extended. If chunking of the data is needed then this should be a generic feature of filebeat, not of the multiline feature.

**Comment by ruflin** [comment]
@ph @jordansissel @guyboertje It would be nice to also get your thoughts on this.

**Comment by guyboertje** [comment]
@ruflin - I think you are spot on. This is a simple FSM really. My only comment is when both start and end are supplied and the FSM is not in the buffering state any lines received are sent as one event per line.

**Comment by urso** [comment]
All in all config looks very reasonable (despite a little more complicated than logstash multiline).

Logstash seems to implement After and Before pattern support only, right?

With simple regex in Start/End pattern be careful e.g. when doing xml. just filtering for '</' is not reliable due to XML essentially being a CF Language (in theory can not fully captured by regular grammars). If you define '^</' (no guarantee xml log is indented though) or know the enclosing tag does not repeat it in body it should work, though. Same for JSON.

Are there any pattern combinations that are not allowed? E.g. After and Before pattern at same time?
What is the semantics of different pattern combinations:

Start + After pattern: Both must match on first line and After pattern from then on

After + Before pattern: Both must match or separate lines

Start + After + Before pattern: Start and After must match on first line + After and Before must match for all lines in multiline event?

Start + After + End pattern: Start and After pattern must match on first line. After pattern must not match on last line if End pattern matches, but on all lines before last line?

We break multiline event into single line events if conditions fail after merging N lines?

**Comment by ruflin** [comment]
@urso I was thinking that the only combination that should be allowed is start/end. That is why I only described these 4 cases above. Not sure if adding more combination will bring a benefit?

Concerning merging: I would do the merging continously. So a maximum of two lines are in the memory. Every time a new line is read, either it is appended to the last line or the (combined) last line is sent. What kind of conditions do you mean by failing after merge?

About XML: It will be up to the user to define the correct syntax for his use case, but we should definitively mention that in the docs.

**Comment by urso** [comment]
> What kind of conditions do you mean by failing after merge?

The line merging is basically a very simple FSM. But what if the FSM detects it does not match the given input after having processed N lines already. For example in this combination 'Start + After + End pattern'. If a line is found with neither After nor End pattern matching we are in an invalid state => the input can not be matched by the state machine. How to handle this. If we won't allow special combination of patterns, then this might be no problem.

**Comment by ruflin** [comment]
@urso I would only allow the above combinations so we would also circumvent this problem. In case the start pattern matches and the end pattern is never found, it will add lines until eof and timeout is reached.

**Comment by urso** [comment]
hm... poor memory usage, but okish.

At least 'Start + After' and 'Start + Before' combinations are still interesting. e.g. Java stack traces? Just 'Start' pattern might not be enough, unless your file consists of stack traces only.

**Comment by ruflin** [comment]
What you mean is that a Java Stack trace and a Java Log message would have the same pattern in the first line? If yes, this case could be covered by "After" I think, but we would have to check some specific examples.

About the memory: Isn't that what we have max_lines and max_bytes for? The question is what happens when it is reached, if the data is dropped or not. Or do you see other memory issues?

**Comment by tsg** [comment]
What would be the equivalent FB config for this LS config?

<pre>
input {
  file {
    path => "/var/log/someapp.log"
    codec => multiline {
      # Grok pattern names are valid! :)
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => previous
    }
  }
}
</pre>

It seems to me like we would also benefit from some sort of `negate` option?

**Comment by tsg** [comment]
Ignore the Grok pattern in the above example, using the equivalent regexp is fine IMHO. I'm just interested in the negation part.

**Comment by ruflin** [comment]
@tsg My easy answer was first as following:

```
before_pattern: "^!%{TIMESTAMP_ISO8601} "
```

But I just realised that the regexp negation can only be applied in a more complex way (look ahead) to more then one character. So the above would not work out of the box and it looks like you are right and the negate option could be much easier for the user to implement.

**Comment by ph** [comment]
@ruflin I think you are spot on and I think you will need to support a `max_lines` and a `max_bytes` options the first hit would trigger a flush.

**Comment by urso** [comment]
@ruflin right max_lines and max_bytes should keep memory usage low.

on Start pattern without End pattern it says:
> The pattern of the first line is known. All follow up lines belong to the first line.
> ...
> All follow up lines which don't match, will be added to the event

So if we have a log file mixing Java Stack traces with other log message:

    [beat-logstash-int-multiple-big-tls-832-2015.11.28] IndexNotFoundException[no such index]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
        at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
    Normal Log line 1
    Yet Another Log line
    Foo
    Bar

Which events will be generated? But in the end it's up to the user to configure this correctly.

**Comment by urso** [comment]
@ruflin When max_lines/max_bytes is hit we can do either way. For now I would flush the buffer, send the event + some note saying the event snapped short (for whatever reason). Who is reading all 100 lines of Java StackTraces? All additonal lines/bytes added by the state machine will be ignored, until state machine finds the multiline-event being 'finished' and a new one starts.

**Comment by ruflin** [comment]
@urso Sounds good to me. The suggested field from my side for this is "truncated". About the Java Stack Trace: Yes, it will be up to the user to configure it correctly. Auto detection seems to me too hard to get it right.

**Comment by ph** [comment]
I wouldnt worry too much about auto detect, we will get it wrong ;)
@urso Java strack trace are big by default, we went with a default of 500 lines.

When the max lines/max bytes were hit we usually tag the event with  a special tag.

```
event.tag "multiline_codec_max_bytes_reached" if over_maximun_bytes?
event.tag "multiline_codec_max_lines_reached" if over_maximun_lines?
```

**Comment by urso** [comment]
I've not been talking about auto-detect. I've just been saying 'Start-pattern' only configuration is mostly 'dangerous', but there is a good reason to have 'Start+End-pattern'  or 'Start-After-pattern' + 'Start+Before-pattern' configs.

If possible we should provide some sample configs.

+1 for tagging. We should use same tags, so migration from LS multiline to filebeat multiline is more straight forward.

**Comment by ruflin** [comment]
Based on the feedback of @tsg it gets obvious, that negate is necessary param to be set. Based on this I worked on three more options on how the multine config could be implemented. `Enhanced LS Pattern` is my preferred option. I ignored the max_bytes and max_lines variables in the examples below.

## Enhanced LS Config

Based on the LS config for multline I suggest to offer the following config options. As a simple configuration only one pattern could be defined. The outcome would be the same as in LS but we would also allow to define start and end.

```
multiline:
  pattern: regexp
  negate: bool
  what: ["start", "end", "before", "after"]
```

An extended version is to use it also as an array. This allows to set multiple patterns at once which makes it more powerful.

```
multiline:
  patterns:
  	- 
  	  pattern: regexp
  	  negate: bool
  	  what: ["start", "end", "before", "after"]
  	-
	  pattern: regexp
  	  negate: bool
  	  what: ["start", "end", "before", "after"]
```

I suggest to implemented in a first step the first config and in a second the array option.


## Logstash Config

The following is the Logstash pattern. It has proven to work in production and is very concise.
The disadvantage is that it doesn't allow to combine multiple patterns. I prefer "Enhanced LS Config" of this one.

```
multiline:
  pattern: regexp
  negate: bool
  what: ["previous", "next"]
```

## Initial Suggestion with negate

Below is an modified version of the initial proposal but with negate. I like it because it is quite readable but it introduces too many config options. The array option of "Enhanced LS Config" offers the same options but in a more concise way. I don't recommend to go with this option.

```
# Enable mutline feature
multiline:
  # See description of start_pattern. Can be used alone and in combination with end_pattern
  start_pattern: regexp
  start_pattern_negate: bool

  # See description of end_pattern. Can be used alone and in combination with start_pattern
  end_pattern: regexp
  end_pattern_negate: bool

  # See description of after_pattern. Can only be used alone
  after_pattern: regexp
  after_pattern_negate: bool

  # See description of before_pattern. Can only be used alone
  before_pattern: regexp
  before_pattern_negate: true
```

**Comment by tsg** [comment]
@ruflin in the examples above, the syntax on `what` means that it is a choice between those options? Or is it really an array where you can select multiple values?

**Comment by tsg** [comment]
Is it correct that `before == next` in LS terms, `after == previous`? And `start` and `end` are new. Did I get it right?

**Comment by ruflin** [comment]
@tsg For the first comment:
* what means only 1 option
* For the second: yes

**Comment by ruflin** [comment]
Based on our discussion we just had we will go with the option "Enhanced LS Config".

**Comment by ruflin** [comment]
Improved option for what:
```
multiline:
  pattern: regexp
  negate: bool
  type: ["start", "end", "before", "after"]
```
