### ISSUE TITLE
elasticsearch plugin always active?

### ISSUE THREAD

**Issue by runningman84** [elastic/filebeat#312]
I get this error starting filebeat:
```
ERR failed to initialize elasticsearch plugin as output: no host configuration found
```
My config looks like this:
```
filebeat:
  prospectors: []
  registry_file: "/var/lib/filebeat/registry"
  config_dir: "/etc/filebeat/conf.d"
output:
  elasticsearch:
    hosts: []
    enabled: false
  logstash:
    enabled: true
    hosts:
    - logstash.loc:5043
/etc/filebeat/filebeat.yml (END)
```
Filebeat should not complain about my elasticsearch config because I did not enable it?
