### ISSUE TITLE
Filebeat SSL Not Working

### ISSUE THREAD

**Issue by tfendt** [elastic/filebeat#329]
I followed this document: [Migrating from Logstash Forwarder to Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/_migrating_from_logstash_forwarder_to_filebeat.html) for converting from logstash-forwarder to file beat and I am getting the following error when trying to start Filebeat:

2016/01/28 17:59:11.733665 transport.go:125: ERR SSL client failed to connect with: read tcp client_ip:27084->server_ip:5043: i/o timeout

This is currently working with logstash-forwarder. Here is my logstash-forwarder config
```YAML
# The path to your client ssl certificate (optional)
    "ssl certificate": "/etc/logstash-forwarder.crt",

    # The path to your client ssl key (optional)
    "ssl key": "/etc/logstash-forwarder.key",

    # The path to your trusted ssl CA file. This is used
    # to authenticate your downstream server.
    "ssl ca": "/etc/logstash-forwarder.crt"
```

Here is my filebeat config:
```YAML
tls:
      # List of root certificates for HTTPS server verifications
      certificate_authorities: ["/etc/logstash-forwarder.crt"]

      # Certificate for TLS client authentication
      certificate: "/etc/logstash-forwarder.crt"

      # Client Certificate Key
      certificate_key: "/etc/logstash-forwarder.key"
```

**Comment by andrewkroh** [comment]
Could you please post the entire Filebeat config file and the logstash config that you are using. Also what versions of Filebeat, Logstash, and logstash-input-beats plugin are you using?

**Comment by tfendt** [comment]
Sure thing. I am using Filebeat 1.0.1, Logstash 2.1.1, Logstash-input-beats 2.0.3.

When you asked about the beats input plugin I realized I was not using it. I updated the logstash config to use it and now I am getting a different error. The new error is:

transport.go:125: ERR SSL client failed to connect with: EOF

Filebeat Config:
```YAML
############################# Filebeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
      paths:
        - /var/log/rewardsvc-service/*.log
        - /var/log/rewardsvc-batch/*.log

      fields:
        environment: prod
        application: rewards-api
        type: log

      input_type: log
      document_type: log

      registry_file: /var/lib/filebeat/registry

############################# Output ##########################################
output:
  ### Logstash as output
  logstash:
    hosts: ["logstash:5043"]

    # Optional TLS. By default is off.
    tls:
      # List of root certificates for HTTPS server verifications
      certificate_authorities: ["/etc/logstash-forwarder.crt"]

      # Certificate for TLS client authentication
      certificate: "/etc/logstash-forwarder.crt"

      # Client Certificate Key
      certificate_key: "/etc/logstash-forwarder.key"

############################# Shipper #########################################

shipper:
  # The name of the shipper that publishes the network data. It can be used to group
  # all the transactions sent by a single shipper in the web interface.
  # If this options is not defined, the hostname is used.
  #name:

  # The tags of the shipper are included in their own field with each
  # transaction published. Tags make it easy to group servers by different
  # logical properties.
  #tags: ["service-X", "web-tier"]

  # Uncomment the following if you want to ignore transactions created
  # by the server on which the shipper is installed. This option is useful
  # to remove duplicates if shippers are installed on multiple servers.
  #ignore_outgoing: true

  # How often (in seconds) shippers are publishing their IPs to the topology map.
  # The default is 10 seconds.
  #refresh_topology_freq: 10

  # Expiration time (in seconds) of the IPs published by a shipper to the topology map.
  # All the IPs will be deleted afterwards. Note, that the value must be higher than
  # refresh_topology_freq. The default is 15 seconds.
  #topology_expire: 15

  # Configure local GeoIP database support.
  # If no paths are not configured geoip is disabled.
  #geoip:
    #paths:
    #  - "/usr/share/GeoIP/GeoLiteCity.dat"
    #  - "/usr/local/var/GeoIP/GeoLiteCity.dat"


############################# Logging #########################################
logging:
  to_files: true

  files:
    path: /var/log/filebeat

    name: filebeat.log

    rotateeverybytes: 10485760

    keepfiles: 7

    # Sets log level. The default log level is error.
    # Available log levels are: critical, error, warning, info, debug
    level: debug
```

Logstash Config:
```YAML
input {
  lumberjack {
    port => 5043
    type => "logs"
    ssl_certificate => "/etc/logstash/logstash-forwarder.crt"
    ssl_key => "/etc/logstash/logstash-forwarder.key"
  }

  beats {
    port => 5044
    type => "logs"
    ssl_certificate => "/etc/logstash/logstash-forwarder.crt"
    ssl_key => "/etc/logstash/logstash-forwarder.key"
  }
}

output {
  redis {
    host => "logstash-redis"
    data_type => "list"
    key => "logstash"
    congestion_interval => 1
    congestion_threshold => 20000000
    workers => 16
    batch => true
    batch_events => 50
    batch_timeout => 5
 }
}
```
