### ISSUE TITLE
Multiple paths with different settings?

### ISSUE THREAD

**Issue by chad-upton** [elastic/filebeat#331]
Does beats support doing something like:

```
filebeat:
  prospectors:
    -
      # Linux system logs
      paths:
        - /var/log/messages
        - /var/log/secure
        - /var/log/cloud-init-output.log
        - /var/log/yum.log
      encoding: utf-8
      input_type: system
      fields:
        json: false
      fields_under_root: true

      # Puma Logs
      paths:
        - /var/log/puma/puma.log
      encoding: utf-8
      input_type: puma
      fields:
        json: true
      fields_under_root: true
```

What I think is happening is it only does a harvester for the last one in the log.  Is there another way I should be doing this?

Thanks!

**Comment by chad-upton** [comment]
Nevermind figured it out.. just in case someone else wants to do this:

```
############################# Filebeat ######################################
filebeat:
  prospectors:
    -
      # Linux system logs
      paths:
        - /var/log/messages
        - /var/log/secure
        - /var/log/cloud-init-output.log
        - /var/log/yum.log
      encoding: utf-8
      input_type: system
      fields:
        json: false
      fields_under_root: true
    -
      # Puma Logs
      paths:
        - /var/log/puma/puma.log
      encoding: utf-8
      input_type: puma
      fields:
        json: true
      fields_under_root: true
```

Just add another prospector as -.
