### ISSUE TITLE
Filebeat backoff_factor does not work

### ISSUE THREAD

**Issue by matglas** [elastic/filebeat#343]
I setup my filebeat to backoff. But the info that is returned is showing that it does not work.

host2_1 is de log from a my Docker container running filebveat.
```
host2_1 | 2016/03/08 10:14:29.715432 single.go:152: INFO send fail
host2_1 | 2016/03/08 10:14:29.715441 single.go:159: INFO backoff retry: 1s
host2_1 | 2016/03/08 10:14:30.715896 single.go:126: INFO Connecting error publishing events (retrying): Head http://localhost:9200: dial tcp [::1]:9200: getsockopt: connection refused
host2_1 | 2016/03/08 10:14:30.715915 single.go:152: INFO send fail
host2_1 | 2016/03/08 10:14:30.715926 single.go:159: INFO backoff retry: 2s
host2_1 | 2016/03/08 10:14:32.716391 single.go:126: INFO Connecting error publishing events (retrying): Head http://localhost:9200: dial tcp [::1]:9200: getsockopt: connection refused
host2_1 | 2016/03/08 10:14:32.716413 single.go:152: INFO send fail
host2_1 | 2016/03/08 10:14:32.716424 single.go:159: INFO backoff retry: 4s
```

Here is my setup.
```
filebeat:
  idle_timeout: 15s
  spool_size: 1024

  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      paths:
        - "/var/log/apache2/access*"
      input_type: log
      backoff: 2s
      max_backoff: 120s
      backoff_factor: 5
```

I using Filebeat 1.1.2.
And I run it with `filebeat -e -v -c=/etc/filebeat/filebeat.yml`

Anyone having the same experience.
