### ISSUE TITLE
config dir only using prospectors from first yml file

### ISSUE THREAD

**Issue by nigelp-vci** [elastic/filebeat#344]
filebeat on windows, using the config_dir correctly loads/fetchs all the additional yml files in the directory.
however only prospectors from the first yml file are actually started

**Comment by ruflin** [comment]
Can you share the content of your config files to make sure the configuration files are correct?

**Comment by nigelp-vci** [comment]
after further testing i've found the following:

Scenario 1: filebeat.yml contains all prospectors. All files logged.
Scenario 2: filebeat.yml contains no prospectors, config_dir contains 2 yml config files: iis, api. Only iis logged
Scenario 3: filebeat.yml contains api prospectors, config_dir contains iis yml config. all fileslogged.
Scenario 4: filebeat.yml contains no prospectors, config_dir contains 1 yml config with 2 prospectors (iis, api). all files logged.

This indicates an problem with config for the api log files, yet these are processed when in the filebeat.yml or the iis.yml

- filebeat.yml - no prospectors:
`
############################# Filebeat ######################################
filebeat:
  prospectors:

  registry_file: "C:/ProgramData/filebeat/registry"
  config_dir: C:\Program Files\filebeat\configs
 
############################# Output ##########################################
output:

  ### Logstash output
  logstash:
    hosts: ["servername:port"]

############################# Shipper #########################################

shipper:
  #tags: ["service-X", "web-tier"]

############################# Logging #########################################

logging:

  #to_syslog: false
  to_files: false
`

- iis.yml - iis prospectors
`
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### IIS logs
    -
      paths:
        - E:\logs\inetpub\LogFiles\*\*.log
      input_type: log
      document_type: iis_log

      ## exclude_lines. By default, no lines are dropped.  (RegEx)
      exclude_lines: ["^#"]

      scan_frequency: 10s
      force_close_files: true
## Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
`
- api.yml - api prospectors
`
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### Api logs
    -
      paths:
        - E:\logs\\api\*.log
      input_type: log
      document_type: api_log

      ## exclude debug and trace lines - filebeat fails RegEx :( << implement on logstash instead
      ##exclude_lines: ["^[\\d-:\\.]* [\\d-:\\.]* (DEBUG|TRACE)"]
      
      exclude_files: ["error"]

      fields:
        source: api
      fields_under_root: false

      scan_frequency: 10s
      force_close_files: true
## Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
`

**Comment by nigelp-vci** [comment]
seems the "write" is reformating the config file entries above

**Comment by ruflin** [comment]
@nigelp-vci Use 3 backticks around the config files for better formatting.

**Comment by nigelp-vci** [comment]
- filebeat.yml - no prospectors

```
############################# Filebeat ######################################
filebeat:
  prospectors:

  registry_file: "C:/ProgramData/filebeat/registry"
  config_dir: C:\Program Files\filebeat\configs

############################# Output ##########################################
output:

  ### Logstash output
  logstash:
    hosts: ["server:port"]


############################# Shipper #########################################
shipper:

############################# Logging #########################################
logging:
  to_files: false
```

**Comment by nigelp-vci** [comment]
- iis.yml 
```
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### IIS logs
    -
      paths:
        - E:\logs\inetpub\LogFiles\*\*.log

		input_type: log
      document_type: iis_log

      exclude_lines: ["^#"]

      scan_frequency: 10s
      force_close_files: true
### Remaing entries are required but ignored::	  
############################# Output ##########################################
# Multiple outputs may be used.
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
```

**Comment by nigelp-vci** [comment]
- api.yml
```
############################# Filebeat ######################################
filebeat:
  prospectors:   
    ### Api logs: 
    -
      paths:
        - E:\logs\api\*.log
        
      input_type: log
      document_type: api_log

      # exclude debug and trace lines <<< filebeat RegEx Fails! << implent @ logstash instead
      #exclude_lines: ["^[\\d-:\\.]* [\\d-:\\.]* (DEBUG|TRACE)"]
      
      exclude_files: ["error"]

      fields:
        source: api
      fields_under_root: false

      scan_frequency: 10s
      force_close_files: true
	  
### Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
```
