### ISSUE TITLE
File beat multiline is not working for XML type of files

### ISSUE THREAD

**Issue by Rajeshkumar123** [elastic/filebeat#347]
Hi,

I am using `logstash 2.2.1` and `logstash-input beats-2.1.3`. I have some XML type of log files. I have written beats config. I am facing two kinds of issues as follows.

**Issue 1**: The xml log file multiline events are not getting combined into single event as expected.
**Issue 2**: Beats keep on fetching the XML files. It's not getting stopped. How to overcome this.

Below is my beats yml file configuration.

```
filebeat:
  prospectors:
    -
      paths:
         - /logs/mylogs/2015*/*.xml
      document_type: server_log
      registry_file: /myarea/config/mylogs/.filebeat	  
  multiline:
    pattern: "^<error"
    negate: true
    match: after
output: 
  logstash:     
     hosts: ["localhost:11689"]
console:
    pretty: true
```

My sample XML log will be in below format

```
<error id="1qas79" host="hhy789">
<snapshot>
<variable name="a">
  <item string="sss"> </item>
</variable>
</snapshot>
</error>
```
